### ISSUE TITLE
[test] Avoid error logging to print noisy output during tests

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-firmware-upgrader#118]
Run tests (notice it outputs a lot of things)

```
 $ ./runtests.py 
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.............................................................{'device': ['Device Firmware with this Device already exists.']}
................................................SoftTimeLimitExceeded raised in batch_upgrade_operation task
..SoftTimeLimitExceeded raised in upgrade_firmware task
.
```

Checkout the following functions:
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_stdout
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_stderr
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_any_output

------------------------

Take reference from https://github.com/openwisp/openwisp-controller/pull/366

**Comment by b-thebest** [comment]
hello, Can I take up this issue and work on it?

**Comment by devkapilbansal** [comment]
Sure @b-thebest, go ahead

**Comment by b-thebest** [comment]
Thank you for the assignment.
I am getting errors while installing it locally.

**Comment by b-thebest** [comment]
@devkapilbansal I have one small doubt. Should I remove full stop logging on console also or only errors ?

**Comment by devkapilbansal** [comment]
It would be better if you can remove those dots too.

**Comment by nemesisdesign** [comment]
Wait a minute, for the dots you mean `..........`? That's the standard behavior and we should not remove it @devkapilbansal @b-thebest

**Comment by RahulPalve** [comment]
hey, I want to work on this
