### ISSUE TITLE
Can't figure out how to update my firmware using this package

### ISSUE THREAD

**Issue by tusharmalpani20** [openwisp/openwisp-firmware-upgrader#129]
I installed OpenWISP along with openwisp-firmware-upgrader module using ansible method.
Remote configuration works just fine but when coming to upgrading the firmware remotely, I just can't figure that part.
Can anyone here help me understand that process.
( I created a category and then a build, but there is no option to actually upload a firmware file and remotely upgrade routers firmware. Am lost.)
Thanks in advance.

**Comment by okraits** [comment]
Please use the mailing list, forums or general chat for user questions. Thank you!
