### ISSUE TITLE
[upload] Store images in private location

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#13]
Right now firmware images are stored in the media folder which is publicly accessible via unauthenticated HTTP (provided one knows the exact URL), we have to find a way to achieve the following:

- firmware images have to be stored in a directory which is not accessible via unauthenticated HTTP requests
- in order to download a file the user must be either superuser or must be a staff user with access to the organization
- if possible, we should put all images of a build in a dedicated directory, this also avoids name collisions, it seem that now images are all saved in one directory, which will most probably cause name collisions

This open source package should help us in achieving this more quickly: https://github.com/edoburu/django-private-storage

**Comment by PabloCastellano** [comment]
I'm working on it
