### ISSUE TITLE
[ci] Fix CI build for django~=3.0.0

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-firmware-upgrader#134]
CI build not working for django~=3.0

![image](https://user-images.githubusercontent.com/56037184/113812819-5c055100-978c-11eb-832b-676ae8aa9cb1.png)

**Comment by devkapilbansal** [comment]
@codesankalp instead of opening issues, create PRs to fix it

**Comment by codesankalp** [comment]
Ok means without referencing an issue I can create PR @devkapilbansal?

**Comment by devkapilbansal** [comment]
> Ok means without referencing an issue I can create PR @devkapilbansal?

Yes, as this issue is already discussed
