### ISSUE TITLE
[bug] Upgrade fail but OpenWISP thought it didn't

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-firmware-upgrader#138]
Not sure if this is a bug or not, but in my virtualbox openwrt testing box,
I tried to upgrade it's firmware and it's failed with the following error:

```bash
root@08-00-27-4F-23-C9:~# sysupgrade -v -c /tmp/openwrt-19.07.7-x86-64-combined-ext4.img.gz
Cannot find '/overlay/upper/etc', required for '-c'
```

Yet, on OpenWISP admin dashboard, It shows upgraded successfully.

If it can happen on real devices, I think it would be a bug.

**Comment by nemesisdesign** [comment]
Thanks for reporting @atb00ker, this issue should be fixed by https://github.com/openwisp/openwisp-firmware-upgrader/pull/128/commits/558448fde216f66804b97733f99efe7153e6f053, can you try to replicate it with the `dev` branch and let me know how it goes?

**Comment by atb00ker** [comment]
It's failing now, not entirely sure if the error is correct though, please check these logs:
```

Status:
failed
Log:
Connection successful, starting upgrade...
Image checksum file found
Checksum different, proceeding with the upload of the new image...
Sysupgrade test passed successfully, proceeding with the upgrade operation...
Upgrade operation in progress...
SSH connection closed, will wait 150 seconds before attempting to reconnect...
Trying to reconnect to device at 192.168.56.2 (attempt n.1)...
Connected! Writing checksum file to /etc/openwisp/firmware_checksum
ash: can't create /etc/openwisp/firmware_checksum: Read-only file system
```

It's complaining Read-only file system after waiting for 150 seconds after the error, and it failed because it couldn't write checksum when `Cannot find '/overlay/upper/etc', required for '-c'` was the primary reason.
What do you think?

**Comment by nemesisdesign** [comment]
Is this the output you get with the `dev` branch? It's better but not what I had expected, I would expect it to fail sooner, although it won't fail if the exit code is of sysupgrade is 1. Can you try running sysupgrade manually and check what exit code you get?

eg:

```
sysupgrade -v -c /tmp/openwrt-19.07.7-x86-64-combined-ext4.img.gz
echo $?
```

**Comment by atb00ker** [comment]
No, I double checked, it's fixed in dev branch, when I tried last, it didn't get detected because of another irrelevant error! 
Closing this.
