### ISSUE TITLE
[fw-upgrade] Add default permissions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#15]
Operator:

- view builds and related images
- view mass upgrade operations and related device operations
- view device firmware objects

Administrator:

- all permission on all objects

Example of how we did it in another module: https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/migrations/0004_default_permissions.py

**Comment by PabloCastellano** [comment]
I'm working on it
