### ISSUE TITLE
How-to compile new firmware?

### ISSUE THREAD

**Issue by mikysal78** [openwisp/openwisp-firmware-upgrader#181]
I have old playbook with [ansible-openwisp2-imagegenerator](https://github.com/openwisp/ansible-openwisp2-imagegenerator/), but i have error to compile.
I try new playbook (paste and copy example of readme) and i have error.
Do you have a guide or a new script to automate builds?
Thanks.

**Comment by nemesisdesign** [comment]
I believe I have answered to a similar question in the support channels, this question is off topic here.
