### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by BlueWaterCrystal** [openwisp/openwisp-firmware-upgrader#182]
Hi,

I keep getting this error, and can't seem to fix it, with multiple browsers.

Tried setting OPENWISP_FIRMWARE_UPGRADER_MAX_FILE_SIZE in playbook.yml to 0, None and 4096 * 1024 * 1024 also tried changing Nginx conf but doesn't do anything either.

image:  `ext4-combined-img`  and `ext4-combined-img.gz`
image size: 120MB

**Comment by nemesisdesign** [comment]
Please look at the following variable in the ansible-openwisp2 README: `openwisp2_firmware_upgrader_max_file_size`: https://github.com/openwisp/ansible-openwisp2. If you keep having issues open an issue there.
