### ISSUE TITLE
Daemon service doesn’t autostart after upgrading firmware via OpenWISP

### ISSUE THREAD

**Issue by sergorl** [openwisp/openwisp-firmware-upgrader#201]
I made custom package with daemon service:

```
#!/bin/sh /etc/rc.common
 
exec >> /root/log 2>&1
echo "STARTED non-lora-aggregator"
set -x

USE_PROCD=1
 
START=99
STOP=99

PROG="/usr/bin/non-lora-aggregator"
 
start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
```
and included it in final firmware.

After command `sysupgrade -v my-firmware.bin` my daemon service `non-lora-aggregator` autostarts and works OK.

But when I upgrade my OpenWRT device with the same `my-firmware.bin` via [OpenWISP](https://openwisp.org/) my daemon service `non-lora-aggregator` doesn't start. By the way, after sending command `reboot` to my device via the same [OpenWISP-controller](https://openwisp.io/docs/user/firmware-upgrades.html) my daemon starts after rebooting the device.

My expectations: all daemon services should autostart despite how I do firmware upgrading via `sysupgrade -v my-firmware.bin` or [OpenWISP-controller](https://openwisp.io/docs/user/firmware-upgrades.html)

Why it happens? Please, help me to fix it.

**Comment by sergorl** [comment]
very strange: after `sysupgrade -c -v <path-to-firmware>` deamon service doesn't autostart, but after `sysupgrade -v <path-to-firmware>` daemon autostarts.

**Comment by okraits** [comment]
From `sysupgrade -h`:

> -c           attempt to preserve all changed files in /etc/

So maybe, when using `sysupgrade -c`, after the upgrade your service might be disabled in `/etc/config/services`.

**Comment by nemesisdesign** [comment]
@sergorl, It's hardly a bug in OpenWISP because the firmware upgrader module doesn't do anything exotic, I replied to your forum post here: https://forum.openwrt.org/t/daemon-service-doesnt-autostart-after-upgrading-firmware-via-openwisp/131462/4 .

**Comment by sergorl** [comment]
@nemesisdesign , are you sure it is a bug of OpenWISP? In my opinion it seems it is a bug of OpenWRT, since command sysupgrade -c -v <path-to-firmware> doesn't work properly.

**Comment by sergorl** [comment]
> @sergorl Did you check the `services` config after a sysupgrade with and without the `-c` option?

@okraits , what do you mean `check the services`?

**Comment by sergorl** [comment]
Hmm, I don't have this file `/etc/config/services` on my device.

**Comment by nemesisdesign** [comment]
Closing as it's not a problem with this specific module of OpenWISP but rather a configuration issue on OpenWrt.
