### ISSUE TITLE
[feature] REST API is missing endpoints for DeviceFirmware

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#206]
Right now it is not possible to do the following:

- CRUD operations of DeviceFirmware objects, eg: `/api/v1/firmware-upgrader/device/[id]/firmware/`
  - When a device firmwre is created or changed (which creates an upgrade operation) we should return the upgrade operation ID to allow clients to check the state of the upgrade
- Read UpgradeOperation objects, eg: `/api/v1/firmware-upgrader/device/[id]/upgrade-operation/`

**Comment by tspare** [comment]
I would like to take a shot on this one but would like the expert's opinion to see whats the right approach.  Any comments are greatly appreciated.
On the (/api/v1/firmware-upgrader/device/[id]/firmware/) endpoint, I think we could go 2 ways:
1.  Follow the pattern in DeviceUpgradeOperationInline and do a search of the  UpgradeOperations and return the UpgradeOperation ID of last XXX upgrades done for the device
2.  Build a separate model per device that saves all the UpgradeOperation done and return the IDs from that model

I am not sure I am on the right track, any suggestion as to the best approach?
