### ISSUE TITLE
[feature] Switch to autocomplete filters and autocomplete organization fields 

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-firmware-upgrader#214]
We have added support of multi-tenant autocomplete filters in https://github.com/openwisp/openwisp-users/pull/331 

We need to update the following filters here: 
- CategoryAdmin
    - Update organization filter to add autocomplete functionality 
- BuildAdmin
    - Update organization filter to add autocomplete functionality 
    - Update category filter to use MultitenantRelatedOrgFilter
- BatchUpgradeOperationAdmin
    - Update organization filter to add autocomplete functionality 
    - Update category filter to use MultitenantRelatedOrgFilter

Let's also change the organization fields of all the admin classes to use autocomplete fields instead of select fields, which do not scale when the number of organization in the system is high.

**Comment by nemesisdesign** [comment]
Let's also change the organization fields of all the admin classes to use autocomplete fields instead of select fields, which do not scale when the number of organization in the system is high.
