### ISSUE TITLE
fallback support?

### ISSUE THREAD

**Issue by bam80** [openwisp/openwisp-firmware-upgrader#239]
Hi,
does the upgrader provide fallback with automatic recovering to previous firmware if the upgrade didn't succeed for some reason?

**Comment by mips171** [comment]
If the previous upgrade didn't succeed, then the device likely wouldn't be online, precluding any connection from OpenWISP. You should probably look into a dual bank flash solution if you want resilience against failed upgrades.

**Comment by nemesisdesign** [comment]
@mips171 is right, there's not much we can do on the OpenWISP side.
