### ISSUE TITLE
More device support?

### ISSUE THREAD

**Issue by Darin755** [openwisp/openwisp-firmware-upgrader#248]
I own several devices and none of them seem to have firmeare upgrade support. This is more of a annoyance than anything but how do I add support for these devices? It seems like it should be trivial but the list of supported devices is quite small compared to the 1800 or so devices supported by openwrt.

**Comment by nemesifier** [comment]
Hi @Darin755,

quoting from the [docs](https://github.com/openwisp/openwisp-firmware-upgrader?tab=readme-ov-file#3-upload-images-to-the-build):

> If you use a hardware model which is not listed in the image types, if the hardware model is officially supported by OpenWRT, you can send us a pull-request to add it, otherwise you can use [the setting OPENWISP_CUSTOM_OPENWRT_IMAGES](https://github.com/openwisp/openwisp-firmware-upgrader?tab=readme-ov-file#openwisp_custom_openwrt_images) to add it.

I hope this helps.

**Comment by Darin755** [comment]
> Hi @Darin755,
> 
> quoting from the [docs](https://github.com/openwisp/openwisp-firmware-upgrader?tab=readme-ov-file#3-upload-images-to-the-build):
> 
> > If you use a hardware model which is not listed in the image types, if the hardware model is officially supported by OpenWRT, you can send us a pull-request to add it, otherwise you can use [the setting OPENWISP_CUSTOM_OPENWRT_IMAGES](https://github.com/openwisp/openwisp-firmware-upgrader?tab=readme-ov-file#openwisp_custom_openwrt_images) to add it.
> 
> I hope this helps.

Unfortunately it doesn't. What would such a PR look like? I read it in the docs but that doesn't help me at all. I don't mind spending a bit of time porting a device

**Comment by pandafy** [comment]
@Darin755 the PR would look something like this https://github.com/openwisp/openwisp-firmware-upgrader/pull/232

**Comment by Darin755** [comment]
Thanks
