### ISSUE TITLE
[fw-upgrade] Allow deleting build without deleting mass upgrade operation

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#27]
Deleting a build should not try to cascade on mass upgrade operation.

But the old build representation should be added to the mass upgrade operation before the build is deleted: something like a hidden field which is used only if the build relation is `None` (has been deleted).

**Comment by nemesisdesign** [comment]
Related to #66, may be duplicate.

**Comment by NayanKanaparthi** [comment]
hey, i want to work on this issue

**Comment by nemesisdesign** [comment]
I have reviewed this requirement and come to the conclusion that is overkill. Sorry!
