### ISSUE TITLE
[fw-upgrade] Remove build dir if empty

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#32]
Since #20, files will be uploaded in a subdirectory which uses the build PK as its name.

Now when files are deleted, empty build directories remain (visible after running tests as well).

We need to update this method to handle this case: https://github.com/openwisp/openwisp-firmware-upgrader/blob/1e9fa26d75a48ae9274c2708ea9a10134a2bb9d0/openwisp_firmware_upgrader/base/models.py#L200-L206

I'd check whether the directory containing the file to remove is named as the `build.pk` and if yes and if the directory is empty, remove the directory as well.

**Comment by PabloCastellano** [comment]
> I'd check whether the directory containing the file to remove is named as the build.pk and if yes and if the directory is empty, remove the directory as well.

@nemesisdesign At the end it was not necessary to check that since self.file.path still contains the path after the file is deleted and because we upload the file to a path generated using build.pk, we are sure that they always match. But let me know if I missed any corner case.
