### ISSUE TITLE
[fw-upgrade] Flag logging strings as translatable

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#35]
The strings used to store log messages in the upgrader class should be translatable, because these lines are then shown to the user.
Look for `self.log(`: https://github.com/openwisp/openwisp-firmware-upgrader/blob/master/openwisp_firmware_upgrader/upgraders/openwrt.py

See the django docs regarding translatable strings: https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#standard-translation

**Comment by morrme** [comment]
Hi! Is this still a reserved issue? Either way, do you require the self.log() be replaced with something like gettext() as in the referenced Django docs?

**Comment by nikhanal** [comment]
Can I work on this issue?
Can you please guide me through because I am new to open source projects

**Comment by nemesisdesign** [comment]
@morrme yes, the abbreviation `_(message)` to be more precise.
@nikhanal all the info is described in the issue description, if you have more specific questions, do not hesitate to ask.

**Comment by nikhanal** [comment]
should it look like self.log._(message)? or self.log(message) should be completely replaced by _(message)?

**Comment by atb00ker** [comment]
@nikhanal , I think it should be `self.log(_(message))`; it's basic python, think about it, it would make sense. :smile:
Let me know if you still need help with it. :smile:
