### ISSUE TITLE
[api] Provide way to know devices which will be upgraded in a mass upgrade operation

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-firmware-upgrader#40]
We may use the OPTIONS HTTP verb, more information at https://reqbin.com/Article/HttpOptions.

**Comment by nemesisdesign** [comment]
I don't remember what we wanted to use OPTIONS for?

**Comment by nemesisdesign** [comment]
Now I remember. It's an idea to provide a way to know which devices will be upgrade in a mass upgrade operation, it's related to #41.

**Comment by PabloCastellano** [comment]
I don't remember well. What is the idea? A new endpoint that supports the OPTIONS method and returns the list of devices that can be upgraded?

By re-reading the definition for the OPTIONS method, it looks to me like it's not meant for this.

What do you think about using an endpoint such as `GET /api/batch-upgrade-operation/upgradeable/` or `GET /api/build/<pk>/upgradeable/` ?

**Comment by PabloCastellano** [comment]
I have sent a draft PR for early comments
