### ISSUE TITLE
[fw-upgrader] Make Image firmware file readonly in admin

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#44]
Prevent users from modifying the firmware image file once it has been uploaded. They will have to create a new one if needed.

**Comment by PabloCastellano** [comment]
@nemesisdesign Do you think removing `change_firmwareimage` permission from Administrator is enough?

**Comment by PabloCastellano** [comment]
Now I realize I misread the title of the issue. Let me know if you like the approach I took in my PR. This way administrators cannot change the type attribute neither.
