### ISSUE TITLE
[api] Make firmware image not editable

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#47]
@PabloCastellano see this: https://github.com/openwisp/openwisp-firmware-upgrader/issues/44

I think we can make the firmware images not editable.
Users will have to delete and recreate it.

This makes several things easier and also makes sense since we want to avoid the situation in which all devices are flashed with an image, then the image file is changed with a different one but the system still believes the devices are using that image (they're not, they'll be using a different one).
So forcing the users to delete the image if they want to change it, also makes the system aware of this.

I think we can do this in the API (we'll do it also in the admin in #44).

This means you can remove this:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/f024859288397f763debd4c9806ca8f82ab7ba23/openwisp_firmware_upgrader/tests/base/test_api.py#L574-L590

And its related functionality.

**Comment by PabloCastellano** [comment]
PR ready
