### ISSUE TITLE
[api] Keep the number of queries low

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#50]
The number of queries can skyrocket if left unchecked.

We should add assertions in the tests to check this.

We'll reuse the same technique across all the modules where we introduce an API.

https://docs.djangoproject.com/en/dev/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries

**Comment by nemesisdesign** [comment]
@PabloCastellano 

> The number of queries differ when SAMPLE_APP=1 is specified. How do we deal with it?

That's surprising, can you find out why please?

**Comment by PabloCastellano** [comment]
This is weird. This gist contains the sql queries made. I'm investigating but have no clue so far

https://gist.github.com/PabloCastellano/95ec12f684343f8093734a6de1cb3e2f
