### ISSUE TITLE
[api] User spanning multiple orgs crashes the API

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#55]
Here's the issue:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/b1238a83ea1a40a60261b9a57a0e1a23debda6e7/openwisp_firmware_upgrader/api/views.py#L34-L37

Instead of expecting one org, we should expect multiple ones, the query should be something like `organization__in=[org1_uuid, org2_uuid]`

**PS**: we need to write some tests using an user which is not superuser, it seems this use case is broken.

**Comment by PabloCastellano** [comment]
PR available: https://github.com/openwisp/openwisp-firmware-upgrader/pull/57

Good news is that using the __in filter reduces also the amount of sql queries!

> PS: we need to write some tests using an user which is not superuser, it seems this use case is broken.

As I understand, the tests are run with an operator user, which is not a superuser
