### ISSUE TITLE
[api] build ID in firmware image URL should be readonly

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#56]
If the API URL is:

`/api/v1/firmware/build/<id>/image/`

It does not make sense allowing to change the build ID, the field should be readonly and figured out implicitly from the URL path.

**Comment by PabloCastellano** [comment]
Have you been able to reproduce it? I have not:

```
http --form PATCH localhost:8000/api/v1/firmware/build/9713f04f-9e2c-4856-a56b-93656a04e7d9/image/ee9cfa48-4fca-4013-bd95-bc61c492dad0/ "Authorization:Bearer $ADMIN_TOKEN" build=9713f04f-9e2c-4856-a56b-93656a04e888

HTTP/1.1 400 Bad Request
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 90
Content-Type: application/json
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "build": [
        "Invalid pk \"9713f04f-9e2c-4856-a56b-93656a04e888\" - object does not exist."
    ]
}

```

Also with the coming changes from https://github.com/openwisp/openwisp-firmware-upgrader/pull/51 ... is it really an issue?

**Comment by nemesisdesign** [comment]
@PabloCastellano sorry I did not write the issue description correctly!
The problem is in the POST, to created the firmware image.
I wrote a script that uploads the image after compilation and specifying the `build` is required when posting, but it shouldn't be right? The build ID is already specified in the URL.

**Comment by PabloCastellano** [comment]
Hmmm that should not happen, check this testcase:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/db8053095c0ea1981a1133d3ee6d95eade08ee93/openwisp_firmware_upgrader/tests/base/test_api.py#L694-L707
