### ISSUE TITLE
[qa] Write admin tests which check the presence of details field in admin UI

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#61]
The sample app models have a details field which is shown in the admin:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/1136746050f98851d0dc0fb75ec37cb1b02bd10b/tests/openwisp2/sample_firmware_upgrader/models.py#L12-L16

But we don't have automated tests for this.

If this feature breaks, we won't know from tests.

Write additional tests in `tests/openwisp2/sample_firmware_upgrader/tests.py` (TestAdmin) to check this.

One test for each admin class being used.

**Comment by ManishShah120** [comment]
@nemesisdesign , I would like to work on this issue.

**Comment by devkapilbansal** [comment]
@ManishShah120 just go ahead. 👍

**Comment by nemesisdesign** [comment]
@ManishShah120 go for it.

**Comment by devkapilbansal** [comment]
@ManishShah120 are you working on this?

**Comment by ManishShah120** [comment]
@devkapilbansal, currently I am working on a different issue. I was thinking to work on this issue after completing that, but if you want to work on this issue go for it. :+1:

**Comment by Purhan** [comment]
I will take up this issue then, I've been wanting to work on this for a while.
