### ISSUE TITLE
[fw-upgrader] Do not delete upgrade operations when FirmwareImage is deleted

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#66]
It should be possible to delete firmware images to free space but history shouldn't be lost.

1. Add a failing test for this case
2. Apply fix, setting on_delete=models.SET_NULL to UpgradeOperation.firmware_image should be enough

**Comment by Purhan** [comment]
I would like to work on this, @nemesisdesign it'd be great if you could provide more information. I went through the [quickstart](https://github.com/openwisp/openwisp-firmware-upgrader#quickstart), created a build, uploaded an image and launched a mass upgrade operation but I'm doing something wrong.
![image](https://user-images.githubusercontent.com/10897423/102493124-b6bd5480-4098-11eb-9e1f-b3f3be696b8f.png)

**Comment by nemesisdesign** [comment]
> I would like to work on this, @nemesisdesign it'd be great if you could provide more information. I went through the [quickstart](https://github.com/openwisp/openwisp-firmware-upgrader#quickstart), created a build, uploaded an image and launched a mass upgrade operation but I'm doing something wrong.
> ![image](https://user-images.githubusercontent.com/10897423/102493124-b6bd5480-4098-11eb-9e1f-b3f3be696b8f.png)

That looks like a bug..! :disappointed:

**Comment by nemesisdesign** [comment]
> > I would like to work on this, @nemesisdesign it'd be great if you could provide more information. I went through the [quickstart](https://github.com/openwisp/openwisp-firmware-upgrader#quickstart), created a build, uploaded an image and launched a mass upgrade operation but I'm doing something wrong.
> > ![image](https://user-images.githubusercontent.com/10897423/102493124-b6bd5480-4098-11eb-9e1f-b3f3be696b8f.png)
> 
> That looks like a bug..!

Cannot replicate this.

Can you describe the exact steps you did for this to show up?

Is any device present in your test system at all?
