### ISSUE TITLE
[admin] upgrade_related parameter is not used

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-firmware-upgrader#81]
https://github.com/openwisp/openwisp-firmware-upgrader/blob/7d90cc69e5a4af39b74bae80c6b3d67c4499d269/openwisp_firmware_upgrader/admin.py#L86-L100

This is the logic simplified:

```
upgrade_all = request.POST.get('upgrade_all')
upgrade_related = request.POST.get('upgrade_related') 
if upgrade_all or upgrade_related:
    batch = build.batch_upgrade(firmwareless=upgrade_all)
```

Should we remove it?

_Originally posted by @PabloCastellano in https://github.com/openwisp/openwisp-firmware-upgrader/pull/73_

**Comment by nemesisdesign** [comment]
I am closing this because I believe it's fine as it is.
